MyClient: open62541.c myClient.c
	gcc -std=c99 open62541.c myClient.c -o myClient
	
#open62541.o: 
#	gcc -c -std=c99 open62541.c -o open62541.o
	
#myClient.o:
#	gcc -c -std=c99 myClient.c -o myClient.o
	
clean:
	rm *.o myClient
	
run:
	./myClient
