MyServer: open62541.c myServer.c
	gcc -std=c99 open62541.c myServer.c -o myServer
	
#open62541.o: 
#	gcc -c -std=c99 open62541.c -o open62541.o

#myServer.o:
#	gcc -c myServer.c
	
clean:
	rm *.o myServer
	
run:
	./myServer
